version: '3.2'

services:
    acl_mysql:
      container_name: 'acl_mysql'
      image: mysql:5.7
      volumes:
        - ./run/var:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "${MYSQL_EXTERNAL_PORT}:${DB_PORT}"
      restart: always
      
    acl_app:
      container_name: 'acl'
      build: .
      links:
        - "acl_mysql"
      depends_on:
        - "acl_mysql"
      ports:
        - "${APP_EXTERNAL_PORT}:${APP_PORT}"
      restart: always